### ISSUE TITLE
Undefined /swagger/doc.json

### ISSUE THREAD

**Issue by orihomie** [swaggo/http-swagger#48]
Hi, I cannot access my swagger UI, this is what I'm getting:
![image](https://user-images.githubusercontent.com/29889683/128987499-dab577d7-7b4c-414b-8c66-90a2d641b832.png)
And this is what I'm doing:
```
func (a *APIHandler) initRoutes() {
	a.router.HandleFunc("/anotherRoute", a.anotherRouteHandler).Methods("GET")

	a.router.HandleFunc("/swagger/", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/swagger/index.html", http.StatusMovedPermanently)
	})
	a.router.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"),
	))
...
```

Logs:
```
2021/08/11 07:25:11 http: panic serving 172.17.0.1:60664: not yet registered swag
goroutine 55 [running]:
net/http.(*conn).serve.func1(0xc0010e66e0)
        /usr/local/go/src/net/http/server.go:1804 +0x153
panic(0x160ebe0, 0xc00013c050)
        /usr/local/go/src/runtime/panic.go:971 +0x499
github.com/swaggo/http-swagger.Handler.func1(0x1a015b0, 0xc0000c2000, 0xc0000ae800)
        /go/pkg/mod/github.com/swaggo/http-swagger@v1.0.0/swagger.go:85 +0x3cd
net/http.HandlerFunc.ServeHTTP(0xc001093a40, 0x1a015b0, 0xc0000c2000, 0xc0000ae800)
        /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000d1f680, 0x1a015b0, 0xc0000c2000, 0xc0000ae200)
        /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rs/cors.(*Cors).Handler.func1(0x1a015b0, 0xc0000c2000, 0xc0000ae200)
        /go/pkg/mod/github.com/rs/cors@v1.8.0/cors.go:219 +0x1b9
net/http.HandlerFunc.ServeHTTP(0xc0010d6440, 0x1a015b0, 0xc0000c2000, 0xc0000ae200)
        /usr/local/go/src/net/http/server.go:2049 +0x44
net/http.serverHandler.ServeHTTP(0xc00108afc0, 0x1a015b0, 0xc0000c2000, 0xc0000ae200)
        /usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc0010e66e0, 0x1a04280, 0xc00128c000)
        /usr/local/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2993 +0x39b
```

I'm running my service via docker by mapping ports between host and container, Docker file is:

```
FROM golang:1.16 AS builder

WORKDIR /app

# Install dependencies
COPY go.mod go.sum ./
RUN go mod download && \
  go get -u github.com/swaggo/swag/cmd/swag

# Copy the code from the host and compile it
COPY . ./
RUN swag init && CGO_ENABLED=0 go build -v -o ./my-service

FROM alpine:3.9

EXPOSE 8080

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/my-service ./
ENTRYPOINT ["./my-service"]
```

What could be wrong here?

**Comment by ubogdan** [comment]
The error is obvious: `HTTP: panic serving 172.17.0.1:60664: not yet registered swag`.

Have you added the generated docs into the import section like this?
```
import {
	_ "github.com/swaggo/http-swagger/example/gorilla/docs" // docs  generated by Swag CLI
}
````

**Comment by orihomie** [comment]
Thanks for reply, I've figured it out by myself and I dont know how this import suddenly wiped out of the code.
